[package]
name = "rivet"
version = "0.1.0"
authors = ["Cole Reynolds <cpjreynolds@gmail.com>"]

[features]
default = []
select = []

[dependencies]
libc = "0.1"
bitflags = "0.3"
time = "0.1"
num = "0.1"
rand = "0.3"
